---
title: Data analytics for germline mutations of Foundation Medicine
output: html_notebook
---

1. Initiations and preparations
```{r}
setwd("C:/Northwell/Research/Projects/CaGMFM")
#source("gentab.R")
library(rcompanion)
library(vcd)
library(DescTools)
library(ggplot2)
library(reshape)
library(dplyr)
```

2. Data loading
```{r}
rm(list=ls())
gc()
dat <- as.data.frame(readxl::read_xlsx(path="../../FM-Peds mutaton project.xlsx"))
gnAD <- as.data.frame(readxl::read_xlsx(path="../../ClinVar/gene_statistics.xlsx"))
nogs <- dim(gnAD)[1]+3 # 26 genes + 3 statistics
coln <- colnames(dat) # extract column names
gnAD.pl <- mutate(gnAD,GBMF.log=log10(gnAD$GBMF))

#scatter plot: RVIS v.s. Our estimation
library(ggfortify)
library(ggrepel)
p0 <- ggplot(gnAD.pl,aes(x=GBMF.log, y=RVIS.rank)) +
  geom_smooth(method=lm) +
  geom_point(shape=1, size=3, color="blue") +
  geom_text_repel(aes(label = Gene, size=0.5)) +
  xlab("log10(GBMF)") + ylab("RVIS rank(%)")
  #geom_text(aes(label=Gene),hjust=0, vjust=0)
summary(lm(RVIS.rank~GBMF.log, data=gnAD.pl))
```

3. Define the variables for data processing
```{r}
gname <- NULL # vector of gene name 
pos1 <- 2 #position of element in the vector
pos2 <- 2 #position of column
mdat <- vector(mode="list",length=nogs)
rowlen <- dim(dat)[1] # the number of row
for (i in 1:nogs) {
  mdat[[i]] <- dat[2:rowlen, pos2:(pos2+2)] # subset the data
  for (j in 1:3) # Convert "chr" into "num"
    mdat[[i]][,j] <- as.numeric(mdat[[i]][,j])
  rownames(mdat[[i]]) <- dat[2:rowlen,1] # assign the row name with cancer types
  colnames(mdat[[i]]) <- c("PEDI","AYA","ADULT")
  gname <- c(gname, coln[pos1])
  pos1 <- pos1+3; pos2 <- pos2+3
}
names(mdat) <- gname #Name the row of each dataframes in the list
TT <- mdat$`TOTAL SAMPLES`
```

3. Collect 4 groups ("General", "PEDS", "AYA" and "ADULT") 
```{r}
#across 26 genes based on gene-based mutation frequency (GBMF)
gbmf.df <- gnAD[,c(1,6,8,9)]
colnames(gbmf.df) <- c("Gene", "Risk", "Tot.pop", "GBMF")
gbmf.cm <- mutate(gbmf.df,Group=rep("General",dim(gbmf.df)[1]))
cancer.ls <-vector(mode="list",3)
for (m in 1:dim(gbmf.df)[1]) {
  for (n in 1:3) {
    geneid <- gbmf.df[m,1]
    grn <- names(mdat[[geneid]])[n]
    if (mdat[[geneid]]["TOTAL",n]==0) {
      print(c(grn,geneid))
      next()
    }
    grate <- mdat[[geneid]]["TOTAL",n]/TT["TOTAL",n]
    out <- c(geneid, mdat[[geneid]]["TOTAL",n], TT["TOTAL",n], grate, grn)
    cancer.ls[[n]] <- rbind(cancer.ls[[n]],out)
  }
}
as.numeric.factor <- function(x) {as.numeric(levels(x))[x]}
all.df <- cancer.ls[[1]]
for (i in 2:3) all.df <- rbind(all.df,cancer.ls[[i]])
all.df <- as.data.frame(all.df)
for (i in 2:4) all.df[,i] <- as.numeric.factor(all.df[,i])
all.df[,1]<- as.character(all.df[,1])
colnames(all.df) <- c("Gene", "Risk", "Tot.pop", "GBMF", "Group")
all.df[,1]<- as.character(all.df[,1])
all.pl.df <- mutate(all.df,
                   low.ci = apply(all.df[c("Risk", "Tot.pop")], 1,
                                  function(y) binom.test(y['Risk'], y['Tot.pop'])$ conf.int[1]),
                   high.ci = apply(all.df[c("Risk", "Tot.pop")], 1,
                                   function(y) binom.test(y['Risk'], y['Tot.pop'])$ conf.int[2])
                   )
# plotting
p1 <- ggplot(data=all.pl.df,aes(x=Gene,y=GBMF, group=Group)) + geom_point() + geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
p1 <- p1 + geom_ribbon(aes(ymin=all.pl.df$low.ci, ymax=all.pl.df$high.ci), linetype=2, alpha=0.1)
#p1 <- p1 + geom_line(aes(x=cancer.types,y=General), linetype=2, alpha=0.8, colour="blue", size=1)
p1 <- p1 + xlab("Cancer types") + ylab("Proportion")

# across 71 cancer types
caty.df <- mdat[[1]]
for (n in 2:dim(gnAD)[1]) caty.df <- caty.df + mdat[[n]]
all.TT <- apply(TT,1,sum)
all.caners <- apply(caty.df,1,sum)
TT.cancers <- as.data.frame(t(rbind(all.caners,all.TT)))
# Filtering & selection
TT.cancers <- TT.cancers[-72,]
sel.TT.cancers <- TT.cancers[TT.cancers$all.caners<1,] # select row=0
TT.cancers <- TT.cancers[TT.cancers$all.caners>0,] # filter "row=0" out
cancer.types <- rownames(TT.cancers)

# stitistical estimation of confidence interval
TT.cancers <- mutate(TT.cancers, Prop = all.caners / all.TT,
                   low.ci = apply(TT.cancers[c("all.caners", "all.TT")], 1,
                                  function(y) binom.test(y['all.caners'], y['all.TT'])$ conf.int[1]),
                   high.ci = apply(TT.cancers[c("all.caners", "all.TT")], 1,
                                   function(y) binom.test(y['all.caners'], y['all.TT'])$ conf.int[2])
                   )
rownames(TT.cancers) <- cancer.types
TT.cancers <- mutate(TT.cancers,General=rep(0.03073605,dim(TT.cancers)[1]))

# plotting
p1 <- ggplot(data=TT.cancers,aes(x=cancer.types,y=Prop, group=1)) + geom_point() + geom_line() + 
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
p1 <- p1 + geom_ribbon(aes(ymin=TT.cancers$low.ci, ymax=TT.cancers$high.ci), linetype=2, alpha=0.1)
p1 <- p1 + geom_line(aes(x=cancer.types,y=General), linetype=2, alpha=0.8, colour="blue", size=1)
p1 <- p1 + xlab("Cancer types") + ylab("Proportion")

```

4. Genes associate with cancers
```{r}
# calculate G-test 
cal.GTest <- function(dt, total, group="PEDS", correct="william") {
  # number of row in the data size from the new "list" object
  rowdim <- dim(dt)[1]; coldim <- dim(dt)[2]
  pv <- vector(mode="numeric",length=(rowdim-1))
  # derive the number of non-Cancer
  nonD <- dt; for (i in 1:coldim) nonD[,i] <- nonD[rowdim,i]-nonD[,i]
  # derive the number of non-Gene
  nonG <- dt; nonG <- total - nonG
  # derive the number of both non-Cancer and non-Gene
  nonT <- dt; for (i in 1:coldim) nonT[,i] <- total[rowdim,i] - nonG[,i] - nonD[,i] - dt[,i]
  job <- vector(mode="list",4)
  job[[1]] <- rep(c("PEDS","AYA","ADULT"), each=4)
  job[[2]] <- rep(rep(c("caner","non-cancer"),each=2),3)
  job[[3]] <- rep(c("Gene","non-Gene"),6)
  for (k in 1:(rowdim-1)) {
    #Contingency Tables
    cct <- NULL
    for (h in 1:coldim) {
      cct <- c(cct, dt[k,h], nonG[k,h], nonD[k,h], nonT[k,h])
    }
    job[[4]] <- cct
    job <- as.data.frame(job)
    colnames(job) <- c("Group", "Disease", "Gene", "Count")
    Tab <- xtabs(Count ~  Disease + Gene + Group, data=job)
    
    # G-test
    GT <- GTest(t(Tab[,,group]), correct="william")
    #need 2 or more non-zero column marginals
    pv[k] <- GT$p.value
  }
  return(pv)
}

# Main code for data analyses
GT.pv <- lapply(mdat[1:26], cal.GTest, TT, group="PEDS")
# convert list into data frame
GT.df<- as.data.frame(GT.pv)
#Name the row of each dataframes
rownames(GT.df) <- dat[2:(rowlen-1),1]
GT.log.df <- -log10(GT.df)
```


5. Data visualization 26 genes across 71 cancer types
   Heatmap and PCA are the major plots
```{r}
## Heatmep plotting
library(ComplexHeatmap)
library(circlize)
# collect total numer of patient for each gene
pos_age <-1 #"1->PEDS", "2->AYA", and "3->"
SS <- mdat[[1]][72,pos_age]
for (i in 2:26) SS <- rbind(SS, mdat[[i]][72,pos_age])
rownames(SS) <- names(mdat)[1:26]
# Plot
ha1 = HeatmapAnnotation(dist1 = anno_barplot(TT[1:71,pos_age], bar_width = 1, gp = gpar(col = NA, fill=c("gray")), #,"yellow","green"
                                             border = FALSE, axis = TRUE))
ha2 = rowAnnotation(dist2 = anno_barplot(SS, bar_width = 1, gp = gpar(col = NA, fill = c("green")), #"red","yellow",
                                         border = FALSE, which = "row", axis = TRUE), width = unit(1, "cm"))
ha_column = HeatmapAnnotation(cn = function(index) {
  cancer = as.numeric(colnames(mat))
  which_decade = which(year %% 10 == 0)
  grid.text(year[which_decade], which_decade/length(year), 1, just = c("center", "top"))
})

Heatmap(t(GT.log.df), name = "-log10(P-value)", col = colorRamp2(c(0,1,2,3), c("white", "cornflowerblue",
                                                                               "yellow", "red")),
        show_row_dend = FALSE, rect_gp = gpar(col= "white"), show_column_names = TRUE,
        row_names_side = "left", row_names_gp = gpar(fontsize = 8), column_names_gp = gpar(fontsize = 10),
        column_title = 'The ACMG genes associate with pan-cancer cross the pediatric group',
        top_annotation = ha1, top_annotation_height = unit(1, "cm")) + ha2


## PCA
library(ggfortify)
library(ggrepel)
#autoplot(prcomp(GT.log.df))
p1 <- autoplot(prcomp(GT.log.df), data=GT.log.df, #label=TRUE, label.size = 3,
         loadings = TRUE, loadings.label = TRUE, loadings.label.size  = 3,
         loadings.colour = 'blue', loadings.label.repel=T)
  geom_text(vjust=-1, label=rownames(GT.log.df)) +
     theme(plot.background=element_blank(),
           panel.background=element_rect(fill='transparent',color='black',size=1),
           legend.text=element_text(hjust=1),
           legend.key=element_blank()) 
p1 + geom_text_repel(aes(label = p1$data$rownames, size=0.5))

```

